# Generated by Django 4.1.7 on 2023-04-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_product_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Availability',
            field=models.CharField(choices=[('In stock', 'In stock'), ('Out of stock', 'Out of stock')], max_length=100, null=True),
        ),
    ]
